# Reference from template-project — not active, kept for GitHub Actions migration reference
parameters:
  - name: environment
    type: string
    default: test
  - name: branch
    type: string
    default: test
  - name: awsAccessKeyId
    type: string
  - name: awsSecretAccessKey
    type: string
  - name: awsRegion
    type: string
  - name: stripeSecretKey
    type: string
  - name: stripePublishableKey
    type: string
  - name: stripeWebhookSecret
    type: string
  - name: hotjarSiteId
    type: string
    default: ""
  - name: gaId
    type: string
    default: ""
  - name: originDataAWSRegion
    type: string
    default: ""
  - name: originDataAWSAccessKeyId
    type: string
    default: ""
  - name: originDataAWSSecretAccessKey
    type: string
    default: ""
  - name: originDataS3BucketName
    type: string
    default: ""
  - name: hsfAdminPassword
    type: string
    default: ""
  - name: requiresAuth
    type: string
    default: ""
  - name: artilleryKey
    type: string
    default: ""
  - name: internalVpcConfig
    type: string
    default: "{}"
  - name: existingDatabaseSecretArn
    type: string
    default: ""
  - name: internalAppsProxyConfig
    type: string
    default: "{}"
  - name: campaignStartDate
    type: string
    default: ""
  - name: campaignEndDate
    type: string
    default: ""
  - name: endOfCampaign
    type: string
    default: ""

stages:
  - stage: DeployBackendStack
    displayName: Deploy Backend Infrastructure Stacks
    jobs:
      - template: cdk-backend-infra.yml
        parameters:
          awsAccessKeyId: ${{ parameters.awsAccessKeyId }}
          awsSecretAccessKey: ${{ parameters.awsSecretAccessKey }}
          awsRegion: ${{ parameters.awsRegion }}
          environment: ${{ parameters.environment }}
          stripeSecretKey: ${{ parameters.stripeSecretKey }}
          stripeWebhookSecret: ${{ parameters.stripeWebhookSecret }}
          originDataAWSRegion: ${{ parameters.originDataAWSRegion }}
          originDataAWSAccessKeyId: ${{ parameters.originDataAWSAccessKeyId }}
          originDataAWSSecretAccessKey: ${{ parameters.originDataAWSSecretAccessKey }}
          originDataS3BucketName: ${{ parameters.originDataS3BucketName }}
          hsfAdminPassword: ${{ parameters.hsfAdminPassword }}
          artilleryKey: ${{ parameters.artilleryKey }}
          internalVpcConfig: ${{ parameters.internalVpcConfig }}
          existingDatabaseSecretArn: ${{ parameters.existingDatabaseSecretArn }}
          internalAppsProxyConfig: ${{ parameters.internalAppsProxyConfig }}
          
  - stage: DeployBackendELTServiceImage
    displayName: Deploy ELT Service Image
    jobs:
      - template: deploy-elt-image.yml
        parameters:
          awsAccessKeyId: ${{ parameters.awsAccessKeyId }}
          awsSecretAccessKey: ${{ parameters.awsSecretAccessKey }}
          awsRegion: ${{ parameters.awsRegion }}
          environment: ${{ parameters.environment }}
          serviceName: elt-service

  - stage: DeployBackendLoadTestingServiceImage
    displayName: Deploy Load Testing Service Image
    jobs:
      - template: deploy-load-testing-image.yml
        parameters:
          awsAccessKeyId: ${{ parameters.awsAccessKeyId }}
          awsSecretAccessKey: ${{ parameters.awsSecretAccessKey }}
          awsRegion: ${{ parameters.awsRegion }}
          environment: ${{ parameters.environment }}
          serviceName: load-testing-service

  - stage: DeployFrontendStack
    displayName: Deploy Frontend Infrastructure Stacks
    dependsOn:
      - DeployBackendStack
    jobs:
      - template: cdk-frontend-infra.yml
        parameters:
          awsAccessKeyId: ${{ parameters.awsAccessKeyId }}
          awsSecretAccessKey: ${{ parameters.awsSecretAccessKey }}
          awsRegion: ${{ parameters.awsRegion }}
          environment: ${{ parameters.environment }}
          stripePublishableKey: ${{ parameters.stripePublishableKey }}
          hotjarSiteId: ${{ parameters.hotjarSiteId }}
          gaId: ${{ parameters.gaId }}
          requiresAuth: ${{ parameters.requiresAuth }}
          campaignStartDate: ${{ parameters.campaignStartDate }}
          campaignEndDate: ${{ parameters.campaignEndDate }}
          endOfCampaign: ${{ parameters.endOfCampaign }}
