# Reference from template-project — not active, kept for GitHub Actions migration reference
parameters:
  awsAccessKeyId: ""
  awsSecretAccessKey: ""
  awsRegion: ""
  environment: ""
  serviceName: ""

jobs:
  - job: DockerDeploy
    displayName: "Docker Deploy"
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - checkout: self
      - script: |
          set -e
          echo "##vso[task.setvariable variable=awsAccountId]$(aws sts get-caller-identity --query Account --output text)"
        displayName: "Get AWS Account ID"
        env:
          AWS_ACCESS_KEY_ID: ${{ parameters.awsAccessKeyId }}
          AWS_SECRET_ACCESS_KEY: ${{ parameters.awsSecretAccessKey }}
          AWS_REGION: ${{ parameters.awsRegion }}

      - script: |
          set -e
          aws ecr get-login-password --region ${{ parameters.awsRegion }} | docker login --username AWS --password-stdin $(awsAccountId).dkr.ecr.${{ parameters.awsRegion }}.amazonaws.com
        displayName: "Login to Amazon ECR"
        env:
          AWS_ACCESS_KEY_ID: ${{ parameters.awsAccessKeyId }}
          AWS_SECRET_ACCESS_KEY: ${{ parameters.awsSecretAccessKey }}
          AWS_REGION: ${{ parameters.awsRegion }}

      - script: |
          set -e
          # Build Docker image
          docker build -t fund-a-scholar-data/${{ parameters.serviceName }}-${{ parameters.environment }}:latest ./backend/src/tasks/${{ parameters.serviceName }}

          # Tag Docker image for ECR
          docker tag fund-a-scholar-data/${{ parameters.serviceName }}-${{ parameters.environment }}:latest $(awsAccountId).dkr.ecr.${{ parameters.awsRegion }}.amazonaws.com/fund-a-scholar-data/${{ parameters.serviceName }}-${{ parameters.environment }}:latest

          # Push Docker image to ECR
          docker push $(awsAccountId).dkr.ecr.${{ parameters.awsRegion }}.amazonaws.com/fund-a-scholar-data/${{ parameters.serviceName }}-${{ parameters.environment }}:latest

          # Set image URI parameter in SSM
          IMAGE_URI=$(awsAccountId).dkr.ecr.${{ parameters.awsRegion }}.amazonaws.com/fund-a-scholar-data/${{ parameters.serviceName }}-${{ parameters.environment }}:latest
          aws ssm put-parameter --name "/fund-a-scholar-data/${{ parameters.serviceName }}-${{ parameters.environment }}" --value $IMAGE_URI --type String --overwrite
          cd ../../
        displayName: "Build, tag, and push Docker image"
